name: Build LOVE2D Game

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup LOVE2D
      run: |
        mkdir C:\love
        Invoke-WebRequest -Uri "https://github.com/love2d/love/releases/download/11.4/love-11.4-win64.zip" -OutFile "C:\love\love.zip"
        Expand-Archive -Path "C:\love\love.zip" -DestinationPath "C:\love"
        echo "C:\love\love-11.4-win64" >> $env:GITHUB_PATH

    - name: Download Libraries
      run: |
        git clone https://github.com/vrld/hump.git
        git clone https://github.com/vrld/suit.git
        git clone https://github.com/vrld/HardonCollider.git
        git clone https://github.com/love2d-community/splashes.git
        Move-Item -Path "hump" -Destination "libraries\hump"
        Move-Item -Path "suit" -Destination "libraries\suit"
        Move-Item -Path "HardonCollider" -Destination "libraries\HardonCollider"
        Move-Item -Path "splashes" -Destination "libraries\splashes"

    - name: Build the game
      run: |
        mkdir build
        # cd build
        # cmd /c "powershell Compress-Archive -Path * -DestinationPath build\game.love"
        cmd /c "powershell Start-Process powershell -ArgumentList 'Compress-Archive -Path * -DestinationPath build\game.love' -Wait"
        dir build
        cd ..
        dir ..

    - name: Create game executable
      run: |
        cd build
        cp ../dev-release-notes.txt .
        
        # Verify that game.love is present
        if (Test-Path -Path "game.love") {
          # Copy the LOVE2D executable and the game.love file
          Copy-Item -Path C:\love\love-11.4-win64\*.dll -Destination . # Copy necessary LOVE2D DLLs

          # Create a new executable by concatenating love.exe and game.love
          $loveExePath = "C:\love\love-11.4-win64\love.exe"
          $gameLovePath = "game.love"
          $outputExePath = "HorizonDriving.exe"
          
          # Create a copy of the LOVE executable
          Copy-Item -Path $loveExePath -Destination $outputExePath
          
          # Append the game.love file to the executable
          $loveExeStream = [System.IO.File]::OpenWrite($outputExePath)
          $gameLoveStream = [System.IO.File]::OpenRead('D:\a\Horizon-Driving\Horizon-Driving\build\game.love') # 'D:\a\Horizon-Driving\Horizon-Driving\build\game.love'
          $gameLoveStream.CopyTo($loveExeStream)
          $gameLoveStream.Close()
          $loveExeStream.Close()
        } else {
          Write-Error "game.love file not found in build directory."
        }

    - name: Package the game
      run: |
        Compress-Archive -Path "HorizonDriving.exe, *.dll, dev-release-notes.txt" -DestinationPath HorizonDriving.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: game-build
        path: 'D:\a\Horizon-Driving\Horizon-Driving\build\HorizonDriving.zip'
